### ISSUE TITLE
using aliases with `allowed_to?` from `Reasons` module does not work

### ISSUE THREAD

**Issue by konto-andrzeja** [palkan/action_policy#134]
It looks like the case described in https://github.com/palkan/action_policy/issues/125 is still failing with `0.5.1` version. I did some investigation and it seems that [allowed_to? from Reasons module](https://github.com/palkan/action_policy/blob/master/lib/action_policy/policy/reasons.rb#L185-L202) is used by default, since [the module is included in ActionPolicy::Base class](https://github.com/palkan/action_policy/blob/master/lib/action_policy/base.rb#L19). Adding `policy.apply(policy.resolve_rule(rule))` [here](https://github.com/palkan/action_policy/blob/master/lib/action_policy/policy/reasons.rb#L193) solves the issue.

### Tell us about your environment

**Ruby Version:** 2.6.6

**Framework Version (Rails, whatever):** 6.0.3.3

**Action Policy Version:** 0.5.1

**Reproduction Script:**
Copied from https://github.com/palkan/action_policy/issues/125:
```ruby
require 'bundler/inline'

gemfile(false) do
  source 'https://rubygems.org'
  gem 'rspec'
  gem 'action_policy'
  gem 'pry-byebug'
  gem 'fuubar'
end

require 'action_policy'

require 'rspec/autorun'

puts ActionPolicy::VERSION

class Policy1 < ActionPolicy::Base
  def update?
    allowed_to?(:update?, record, with: Policy2)
  end
end

class Policy2 < ActionPolicy::Base
  def manage?
    true
  end

  alias_rule :update?, to: :manage?
end

class Controller
  include ActionPolicy::Behaviour

  authorize :user

  attr_reader :user

  def initialize(user)
    @user = user
  end

  def call(record)
    authorize!(record, to: :update?, with: Policy1)
  end
end

RSpec.describe 'allowed_to? calling aliased rule' do
  it 'causes an error' do
    user = Object.new
    record = Object.new
    controller = Controller.new(user)

    expect { controller.call(record) }.not_to raise_error
  end
end
```

### What did you do?
Used `allowed_to?` from a policy rule with an alias.

### What did you expect to happen?
Getting `true` or `false`.

### What actually happened?
`NoMethodError` was raised.

**Comment by palkan** [comment]
Thanks for the report!
Should be fixed now, try 0.5.2.

**Comment by konto-andrzeja** [comment]
@palkan Thanks for addressing it so quickly, however it still does not seem to work. It looks like there's still the old code in `ruby/2.6.6/gems/action_policy-0.5.2/lib/.rbnext/3.0/action_policy/policy/reasons.rb` and that's what's used, not `ruby/2.6.6/gems/action_policy-0.5.2/lib/action_policy/policy/reasons.rb`, which has the newest code.

**Comment by palkan** [comment]
Yeah, you're right 😞

Pushed 0.5.3

**Comment by konto-andrzeja** [comment]
Works now, thanks!
